version: '3.8'

services:
  postgres:
    image: postgis/postgis:14-3.4
    container_name: sponty-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sponty
      POSTGRES_USER: sponty
      POSTGRES_PASSWORD: sponty
    ports:
      - "5435:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
