version: '3.8'

services:
  backend:
    image: registry.solidtech.vn/sponty-backend
    container_name: sponty-backend
    env_file:
      - .env
    ports:
      - '18081:8081'
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    volumes:
      - ./data/uploads:/app/uploads

  redis:
    image: redis:7
    container_name: sponty-redis
    restart: unless-stopped
    ports:
      - '6385:6379'
    volumes:
      - ./data/redis:/data
